module.exports = {
  "keyCodes": {
    "BACKSPACE": 8
  },
  "actions" : {
    "ALERT_MESSAGES_CLEAR": "clearAlertMessages",
    "FIELD_VALUE_CHANGE": "fieldValueChange",
    "FIELD_GROUP_VALUE_CHANGE": "fieldGroupItemChange",
    "FIELD_VALIDATION_ERROR": "fieldValidationError",
    "COMPONENT_REMOVE": "componentRemove",
    "COMPONENT_EDIT": "componentEdit",
    "COMPONENT_ADD": "componentAdd",
    "COMPONENT_VISIBILITY" : "componentVisibility",
    "SEND_OPTIONS": "sendOptions",
    "SEND_RESOURCE_OPTIONS": "sendResourceOptions",
    "SEND_CUSTOM_OPTIONS": "sendCustomOptions",
    "LOAD_OPTIONS": "loadOptions",
    "TREE_LOAD_PAGE": "treeLoadPage",
    "WORKFLOW_PREVIOUS_PAGE": "workflowPreviousPage",
    "WORKFLOW_NEXT_PAGE": "workflowNextPage",
    "WORKFLOW_LOAD_PAGE": "workflowLoadPage",
    "GET_SESSION_VALUES": "getSessionValues",
    "VALIDATE": "validate",
    "SESSION_VALUES_LOADED": "sessionValuesLoaded",
    "API_COMMUNCATION_ERROR": "apiCommunicationError",
    "TOGGLE_DISABLE_WORKFLOW_PAGE" : "toggleDisableWorkflowPage",
    "MOVE_WORKFLOW_PAGE" : "moveWorkflowPage",
    "NEST_WORKFLOW_PAGE" : "nestWorkflowPage",
    "UNNEST_WORKFLOW_PAGE" : "unNestWorkflowPage",
    "GET_FIELD_VALUE" : "getFieldValue",
    "SET_FIELD_VALUE" : "setFieldValue",
    "FIELD_VALUE" : "fieldValue",
    "FIELD_BLUR": "blurField",
    "MODAL_HIDE" : "hideModal",
    "ENTRYLIST_FORM_SHOW": "showEntryListForm",
    "ENTRYLIST_ENTRY_EDIT": "editEntryListEntry",
    "ENTRYLIST_ENTRY_REMOVE": "removeEntryListEntry",
    "ENTRYLIST_NEW_ENTRY_ADD": "addNewEntryListEntry",
    "FILE_UPLOAD_PREVIEW_REMOVE": "removeFileUploadPreview"
  }
};
