module.exports = {
	accordion: require('./Accordion'),
	accordionpanel: require('./AccordionPanel'),
	action: require('./Action'),
	alert: require('react-bootstrap').Alert,
	content: require('./Content'),
	contentEditor: require('./ContentEditor'),
	date: require('./Date'),
	entrylist: require('./EntryList'),
	field: require('./Field'),
	fieldGroup: require('./FieldGroup'),
	fieldLabel: require('./FieldLabel'),
	fieldset: require('./Fieldset'),
	file: require('./File'),
	form: require('./Form'),
	grid: require('./Grid'),
	page: require('./Page'),
	panel: require('react-bootstrap').Panel,
	terms: require('./Terms'),
	tree: require('./Tree'),
	workflow: require('./Workflow'),
	workflowitem: require('./WorkflowItem')
};
